# Generated by Django 5.0.6 on 2024-06-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NyaaaStore', '0002_rename_carrito_cart_rename_carritoitem_cartitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tp_producto',
            field=models.CharField(choices=[('ACCESORIO', 'ACCESORIO'), ('POLERA', 'POLERA'), ('SIN ESPECIFICAR', 'SIN ESPECIFICAR'), ('FIGURA', 'FIGURA')], default='SIN ESPECIFICAR', max_length=15),
        ),
        migrations.AlterField(
            model_name='userperfil',
            name='city',
            field=models.CharField(choices=[('Valparaíso', 'Valparaíso'), ('Concepción', 'Concepción'), ('Santiago', 'Santiago'), ('Tome', 'Tome'), ('San Pedro', 'San Pedro')], max_length=15),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('EN PREPARACIÓN', 'EN PREPARACIÓN'), ('PREPARADO', 'PREPARADO'), ('ENTREGADO', 'ENTREGADO'), ('ENVIADO', 'ENVIADO')], default='EN PREPARACIÓN', max_length=30),
        ),
    ]
