# Generated by Django 5.0.6 on 2024-06-28 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NyaaaStore', '0003_alter_producto_tp_producto_alter_userperfil_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400000)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='userperfil',
            name='city',
            field=models.CharField(choices=[('Tome', 'Tome'), ('San Pedro', 'San Pedro'), ('Valparaíso', 'Valparaíso'), ('Santiago', 'Santiago'), ('Concepción', 'Concepción')], max_length=15),
        ),
    ]
